sudo systemctl restart vicon_data_collector.service
sudo systemctl restart setpoint_data_collector.service
sudo systemctl restart estimation_data_collector.service
sudo systemctl restart viser.service
